name: check

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  main:
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
      - run: go install golang.org/x/lint/golint@latest
      - run: golint -set_exit_status ./...
