name: lint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0
