name: test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.18
          - 1.19
          - 1.20
          - 1.21
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./...
